version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      BASE_URL: 0.0.0.0
      PORT: 8080
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/
      REDIS_PORT: 6379
      SELENIUM_PORT: 4444
      SELENIUM_HOST: selenium
      ASSETS_FOLDER: /var/lib/snap-shot/data
      SELENIUM_MAX_INSTANCES: 4
    depends_on:
      - postgres
      - redis
      - selenium
    volumes:
      - ../api-data/app:/var/lib/snap-shot/data
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      VITE_API_BASE_URL: http://api:3307/api
  redis:
    image: redis
    container_name: redis-snap-shot
    ports:
      - '6379:6379'
    volumes:
      - ../redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ../postrgress/pgdata:/var/lib/postgresql/data
  selenium:
    image: selenium/standalone-chrome:latest # Using the specified image
    platform: linux/x86_64
    shm_size: "4g" # Shared memory size
    dns:
      - 8.8.8.8 # DNS settings
    ports:
      - "4444:4444" # Port mapping
      - "7900:7900" # Port mapping
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=false
      - SE_SCREEN_DPI=100
