/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/snap-shots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["handle_get_snapshot_history"];
        put?: never;
        post: operations["handle_snapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snap-shots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["handle_get_snapshot_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DiffImage: {
            color_diff: components["schemas"]["SnapShotBatchImage"];
            lcs_diff: components["schemas"]["SnapShotBatchImage"];
            new: components["schemas"]["SnapShotBatchImage"];
            old: components["schemas"]["SnapShotBatchImage"];
        };
        SnapShotBatch: {
            /** Format: date-time */
            created_at: string;
            created_image_paths: components["schemas"]["SnapShotBatchImage"][];
            deleted_image_paths: components["schemas"]["SnapShotBatchImage"][];
            diff_image: components["schemas"]["DiffImage"][];
            /** Format: uuid */
            id: string;
            name: string;
            new_story_book_version: string;
            old_story_book_version: string;
        };
        SnapShotBatchImage: {
            /** Format: double */
            height: number;
            name: string;
            path: string;
            /** Format: double */
            width: number;
        };
        SnapShotParams: {
            new: string;
            old: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    handle_get_snapshot_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Partner account was created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapShotBatch"][];
                };
            };
        };
    };
    handle_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapShotParams"];
            };
        };
        responses: {
            /** @description Creates snap shots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapShotBatch"];
                };
            };
        };
    };
    handle_get_snapshot_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Historical Item Id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Partner account was created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapShotBatch"][];
                };
            };
        };
    };
}
