// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnapShotBatchJobStatus } from "./SnapShotBatchJobStatus";

export type SnapShotBatchJob = { id: string, snap_shot_batch_id: string, status: SnapShotBatchJobStatus, progress: number, created_at: string, updated_at: string, };
